# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='código')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='nome')),
                ('address', models.CharField(max_length=500, verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=500, verbose_name='código')),
                ('size', models.PositiveSmallIntegerField(default=0, verbose_name='tamanho')),
                ('year', models.PositiveSmallIntegerField(default=0, verbose_name='ano letivo')),
                ('semester', models.PositiveSmallIntegerField(default=0, verbose_name='semestre')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=500, verbose_name='nome')),
                ('workload', models.PositiveSmallIntegerField(default=0, verbose_name='carga horária')),
                ('semester_number', models.PositiveSmallIntegerField(default=0, verbose_name='semestre')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=50, verbose_name='abreviação')),
                ('name', models.CharField(max_length=500, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('start_time', models.TimeField(verbose_name='hora inicial')),
                ('end_time', models.TimeField(verbose_name='hora final')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=50, verbose_name='abreviação')),
                ('name', models.CharField(max_length=500, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='ProgramLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Nível do Curso',
                'verbose_name_plural': 'Níveis dos Cursos',
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20, verbose_name='descrição')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProgramLevel')),
            ],
            options={
                'verbose_name': 'Nível do Curso',
                'verbose_name_plural': 'Níveis dos Cursos',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Tipo do Requisito',
                'verbose_name_plural': 'Tipos dos Requisitos',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='código')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='capacidade')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Tipo da Sala',
                'verbose_name_plural': 'Tipos das Salas',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Day', verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Day', verbose_name='dia')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Room', verbose_name='Sala')),
                ('s_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Class', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Alocação da turma em sala',
                'verbose_name_plural': 'Alocações das turmas em salas',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(verbose_name='hora inicial')),
                ('end_time', models.TimeField(verbose_name='hora final')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Period')),
            ],
            options={
                'verbose_name': 'Intervalo de Tempo',
                'verbose_name_plural': 'Intervalos de Tempo',
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='time_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TimeInterval', verbose_name='Intervalo de Tempo'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TimeInterval', verbose_name='Intervalos de Tempo'),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.RoomType', verbose_name='Tipo da Sala'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.RequirementType', verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProgramType'),
        ),
        migrations.AddField(
            model_name='day',
            name='time_intervals',
            field=models.ManyToManyField(to='manager.TimeInterval', verbose_name='Intervalos de Tempo'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='schedules',
            field=models.ManyToManyField(to='manager.Schedule', verbose_name='Cronogramas'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Teacher', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Institution', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='area',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Campus', verbose_name='Campus'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('day', 'time_interval', 'room')]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('day', 'time_interval')]),
        ),
    ]
